version: '3.8'
services:

    symfony:
        build: volumes/symfony/config
        container_name: symfony_docker
        ports:
            - "8245:80"
        volumes:
            - ./volumes/symfony/config/vhosts:/etc/apache2/sites-enabled
            - ./symfony_project:/var/www/symfony_project

    # maildev:
    #     image: maildev/maildev
    #     container_name: maildev_docker
    #     command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    #     ports:
    #         - "8081:80"
    #     restart: always
    #     networks:
    #         - dev

    database:
        image: mariadb:10.8.2
        container_name: mariadb_docker
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./volumes/database/conf/my.cnf:/etc/mysql/my.cnf
            - ./volumes/database/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '!msg'

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker
        restart: always
        ports:
            - "8336:80"
        environment:
            - "PMA_HOST=172.25.0.2"

    caddy:
        image: dunglas/mercure
        container_name: mercure_docker
        restart: unless-stopped
        environment:
            # Uncomment the following line to disable HTTPS
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
            MERCURE_EXTRA_DIRECTIVES:
                cors_origins "http://localhost:3000"
                cors_origins "http://localhost:8245"
                # anonymous
        # Uncomment the following line to enable the development mode
        # command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
        ports:
            - "9080:80"
            - "9443:443"
        # volumes:
            # - caddy_data:/data
            # - caddy_config:/config

# volumes:
#     db-data:
#     caddy_data:
#     caddy_config: